/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

/**
 *
 * @author juan david carrilllo
 */
public class Instrucciones extends javax.swing.JFrame {

    /**
     * Creates new form Instrucciones
     */
    public Instrucciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelobjetivos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Button_back = new javax.swing.JButton();
        button_next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelobjetivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/objeivos.png"))); // NOI18N
        getContentPane().add(jLabelobjetivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 380, 100));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Este juego se divide en dos fases.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 124, 360, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("la misión del jugador sera atacar a los enemigos que vea en pantalla por medio de bombas. Tenga en");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 630, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("La primera fase es ofensiva y ocurre durante los primeros segundos del juego,durante los cuales ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 630, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("cuenta que las bombas podran matarlo a usted también, así   como los enemigos,  a pesar de ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 620, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText(" su comportamiento poco hostil. Pasados 25 segundos entraremos a la segunda fase del juego ,");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 620, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("la cual detectaremos por que se rompen todos los muros y los enemigos alcanzan un estado de");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 620, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("de euforia que los  obliga a perseguirte por todo el mapa hasta matarte.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 620, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Entre mas tiempo consiguas sobrevivir, mayor sera tu puntaje Final. Buena Suerte ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 620, 50));

        Button_back.setBackground(new java.awt.Color(0, 0, 0));
        Button_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back .png"))); // NOI18N
        Button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backActionPerformed(evt);
            }
        });
        getContentPane().add(Button_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 110, 50));

        button_next.setBackground(new java.awt.Color(0, 0, 0));
        button_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/next  .png"))); // NOI18N
        button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nextActionPerformed(evt);
            }
        });
        getContentPane().add(button_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 110, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gameplaydos.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 400, -1));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondo_instr.jpg"))); // NOI18N
        getContentPane().add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_Button_backActionPerformed

    private void button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nextActionPerformed
        Movimiento movimiento = new Movimiento();
        movimiento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_nextActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_back;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JButton button_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelobjetivos;
    // End of variables declaration//GEN-END:variables
}
