/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import businessLogic.Game;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author juan david carrilllo
 */
public class Menu extends javax.swing.JFrame {
    private TablaPuntajes tabla;
//     Logger.getRootLogger().setLevel(Level.OFF);

    public TablaPuntajes getTabla() {
        return tabla;
    }
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlbTitulo = new javax.swing.JLabel();
        jButtonGame = new javax.swing.JButton();
        jButtonInstrucciones = new javax.swing.JButton();
        jButtonBestScore = new javax.swing.JButton();
        jlbGif = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JlbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 0));

        jlbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BomberMan.png"))); // NOI18N
        jlbTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jlbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jButtonGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/IniciarJuego.png"))); // NOI18N
        jButtonGame.setBorderPainted(false);
        jButtonGame.setContentAreaFilled(false);
        jButtonGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGameActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, 110));

        jButtonInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instrucciones.png"))); // NOI18N
        jButtonInstrucciones.setBorderPainted(false);
        jButtonInstrucciones.setContentAreaFilled(false);
        jButtonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 240, 90));

        jButtonBestScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Tablas.png"))); // NOI18N
        jButtonBestScore.setBorderPainted(false);
        jButtonBestScore.setContentAreaFilled(false);
        jButtonBestScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBestScoreActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBestScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 430, 110));

        jlbGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/source.gif"))); // NOI18N
        getContentPane().add(jlbGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Salirmenu.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 240, 110));

        JlbFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondoimage.jpg"))); // NOI18N
        JlbFondo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JlbFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JlbFondo.setPreferredSize(new java.awt.Dimension(900, 860));
        getContentPane().add(JlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1000, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGameActionPerformed

        
         Game game = null;
        try {
            game = new Game();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        Thread gameThread=new Thread(game);
        gameThread.start();
        this.dispose();
        
        /*
        
        Board board=Control.generarEscenario();
        Game game = null;
        try {
            game = new Game(board);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        Thread gameThread=new Thread(game);
        gameThread.start();
        
        
*/
    }//GEN-LAST:event_jButtonGameActionPerformed

    private void jButtonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstruccionesActionPerformed
      Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonInstruccionesActionPerformed

    private void jButtonBestScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBestScoreActionPerformed
        System.out.println("hola no queiro hacer nada");
         tabla = null ;
        
        try {
            tabla = new TablaPuntajes();
            tabla.getjPanel1().setVisible(false);
        } catch (IOException ex) {
           // Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabla.setLocationRelativeTo(null);
        tabla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBestScoreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Menu().setVisible(true);
                Menu menu = new Menu();
                
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbFondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBestScore;
    private javax.swing.JButton jButtonGame;
    private javax.swing.JButton jButtonInstrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbGif;
    private javax.swing.JLabel jlbTitulo;
    // End of variables declaration//GEN-END:variables
}
